# Generated by Django 3.1.1 on 2020-09-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200919_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='store.Product'),
        ),
    ]
