# Generated by Django 3.1.1 on 2020-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200920_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='store.Product'),
        ),
    ]
