# Generated by Django 3.1.1 on 2020-09-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='store.NewOrderItem'),
        ),
    ]
